# Generated by Django 3.1.4 on 2020-12-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='top',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
