# Generated by Django 3.1.4 on 2020-12-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201205_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
