# Generated by Django 3.1.4 on 2020-12-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201205_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.IntegerField(default=0)),
                ('note2', models.IntegerField(default=0)),
            ],
        ),
    ]
